#!/bin/bash

set -e

IMAGE="gcr.io/hfdbe-416102/harris-family-designs-backend:v1"
SERVICE="harris-family-designs-backend"
REGION="us-central1"
PLATFORM="managed"


# Ensure Docker Buildx is enabled
docker buildx create --use || true

# Build the x86_64 image
docker buildx build --platform linux/amd64 -t $IMAGE --output type=docker .

# Push the image to your Docker registry
docker push $IMAGE

echo "Updating the Google Cloud Run service with the new image..."
gcloud run services update $SERVICE --image=$IMAGE --region=$REGION --platform=$PLATFORM

echo "Deployment complete."

