development:
  hfd:
    host: 'hfd.localhost'
    port: 5173
    scheme: 'http'
  secondhand:
    host: 'secondhand.hfd.localhost'
    port: 8081
    scheme: 'http'

production:
  hfd:
    host: 'www.harrisfamilydesigns.com'
    scheme: 'https'
  secondhand:
    host: 'secondhand.harrisfamilydesigns.com'
    scheme: 'https'
