name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate Docker with Google Container Registry
      run: |
        echo "${{ secrets.GCLOUD_SERVICE_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/harris-family-designs-backend:latest .

    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/harris-family-designs-backend:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy harris-family-designs-backend \
          --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/harris-family-designs-backend:latest \
          --region us-central1 \
          --platform managed \
          --quiet
